version: '3.5'
services:
  nest-crud-db:
    image: mysql:8
    container_name: nest_crud_db
    environment:
      MYSQL_DATABASE: 'crud_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'strongrootpassword'
    ports:
      - "3306:3306"